### PR TITLE
homework threads

### PR DESCRIPTION
**Pull request by BohdanKryven**

### CODE REVIEW

**Comment by BogdanKryven** [comment]
updated

**Review by BohdanKryven — COMMENTED** [review]
ok

**Review by BohdanKryven — COMMENTED** [review]
ok

**Review by BohdanKryven — COMMENTED** [review]
ok

**Review by BohdanKryven — COMMENTED** [review]
ok

**Review by BohdanKryven — COMMENTED** [review]
its ok

**Pull request merged**
